# Generated by Django 4.1.2 on 2023-01-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chat_pfp_link_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='code',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
